### ISSUE TITLE
Mining Ethereum for the first time on test.net have a balance but can't transfer it

### ISSUE THREAD

**Issue by AmesEla** [ethereum/mist#2142]
Hi,

I'm a newbie miner using Mac OS 10.9.6
Ethereum wallet - the latest 0.8.9 
Node type: geth 1.5.9 Go

I am mining Ethereum and tried to transfer a portion leaving some in the account - but it says I don't have enough gas even though the transfer is far less than what it says I've mined 

I also tried to look up this account and it doesn't show on EtherScan
 
Not sure why and how to circumvent. See screen shot.

![screen shot 2017-04-12 at 10 09 52 pm](https://cloud.githubusercontent.com/assets/5491083/24991046/06391efe-1fcd-11e7-9e15-c15621e30c89.png)

![screen shot 2017-04-12 at 10 17 36 pm](https://cloud.githubusercontent.com/assets/5491083/24991192/f6e54634-1fcd-11e7-85df-18469257bb23.png)

**Comment by luclu** [comment]
Please wait until your node is fully synced and try again.
I will close this for now as it should solve it.

**Comment by AmesEla** [comment]
My node is synched - at least the master nose was and my node on the mining side was synched hence mining 

I'm confused by your lack of instructions on why you think it is not synched.

Please do not close this thread as the question was not answered and this did not solve my issue 
___________________________
The only constant is change.

**Comment by AmesEla** [comment]
here is the screenshot of my now missing Ether - there is no record left here nor on the EtherScan sites


![screen shot 2017-04-13 at 12 37 23 pm](https://cloud.githubusercontent.com/assets/5491083/25021845/716257ba-2048-11e7-958d-d4b07f8676a9.png)

**Comment by joediaz1** [comment]
This wallet is killing my ethereum experience like for real. I'm using the latest version I deleted the chain data and reopened it in it starts to sync in fast mode for the first million blocks. after that for the remaining 2 million blocks its on super super slow mode.  like over 24 hours now and still its got 1 million to go. the computer never restored or shut down i never closed the wallet as I know this sets it back into the slow sync. I'm on the latest version of macs OS. I've checked my firewalls checked most things in the check.

**Comment by joediaz1** [comment]
I can allso see that my wallet has some ether in it in the ether scan. and last time even after a week of syncing and when it said it was synced. it still showed a 0 balance. like there is just something not working like something on the mac maybe. maybe it needs to be updated for these problems every one seems to have them.

**Comment by luclu** [comment]
@AmesEla judging from your screenshot you are running in "Test-net" mode. Please switch to the mainnet via the menu `develop -> network`.

**Comment by AmesEla** [comment]
Thanks Luca

I did all of that on both ends - and the ledge updated.

The ether never returned. I then mined another 39 and transferred to my main account but the ether did not appear - it's been a few days and both are up to date.

I would like to get back that ether for contract testing but have also given up and it had been a huge time suck (!) and energy suck on my computer. If this is easy to revert - let me know 

I was also not aware that the ether from  test-net mining is worthless! Zero value 

A few questions and suggestions on that: 
1. The suggestion is for your FaQ where you instruct folks on test mining - make it clear the ether has no value. You probably have but it was not obvious anywhere I looked and took weeks to discover after much pain and wasted energy.

2. Can you recommend how I may actually mine real ether?

3. How much slower is mining ether than test net mining (so I can gleen potential results)? I have already filled out the form that helps you determine computer khz and energy costs - I'm wondering if there is a simple ratio to compare as I was able acquire much test net ether quickly and want to manage my hopeful expectations 

Thanks!
