### ISSUE TITLE
Ethereum wallet hung on creating wallet contract

### ISSUE THREAD

**Issue by Gunna01** [ethereum/mist#3001]
Updated Ethereum Wallet to v9.0

Attempted to create a wallet contract, accepted the required ether\gas price, entered my password and the amount was deducted from my balance and now it has hung for over 15 hours creating the wallet contract. It's also stopped processing transactions but my wallet is in sync. My last 2 transactions have 0 of 12 confirmations but checking the TXID from 15 hours ago has many block confirmations

Closing the wallet and reopened has not resolved the issue.

Transaction for the creation is on the block chain and has many block confirmations
![capture](https://user-images.githubusercontent.com/28095206/29848958-2cb1c524-8d67-11e7-9240-acc262acc3a6.PNG)

edit: After closing and reopening ALL my listed transaction now appear as greyed out and have 0 of 12 confirmations despite previously been marked as complete

**Comment by alexchuvand** [comment]
I have the same issue on Ethereum Wallet v9.0 in the Rinkeby test network.
I created 2 accounts. I have tried to transfer ether between accounts but it keeps being unsuccessful. The number of confirmations stays at 0 for 2-3 min, then the transaction disappears. 
The attempt to create a wallet contract is stuck as well.

**Comment by jameszuroske** [comment]
I also have the same issue on v9.0 on the main network.

I tried both creating a wallet contract and deploying a contract.  The wallet contract is stuck on creating... and the other contract is stuck on executing with 0 out of 12 confirmations even though etherscan.io showed 47 confirmations at 20 mins.

Also tried closing and reopening the wallet.

**Comment by Gunna01** [comment]
So not an isolated issue. I've stopped using my wallet until this gets resolved and would recommedn others do the same. How can we view wallet contracts outside Ethereum Wallet?

**Comment by Klop89** [comment]
I am having the same problem.

https://github.com/ethereum/mist/issues/3012

Nobody here that can resolve the syncing issue?

**Comment by Klop89** [comment]
@gluk256 

https://www.myetherwallet.com/

You can import your wallet to here. I haven't tried it yet. Need to read into it.

**Comment by Gunna01** [comment]
Where are the devs. Why has no one responded who can fix the issue?

**Comment by cross** [comment]
I'm also having this problem.  Ethereal wallet 0.9.0 on Mac.  I sync'd/loaded the full chain with geth manually, so the full U/I would show up.  And, days/weeks earlier created a main account.  But, I'm unable to create a wallet contract.  When I click "Add Wallet Contract" in the main (Wallets) interface, it will let me set a name, and i'm selecting a single owner contract, but then the main windows just shows it creating.  I left one for a few hours, then later based on other google results of other people reporting similar problems, tried another one.  But, I now have two contracts stuck saying "Creating ..."

Has anyone found a way to deal with this?  I have experience with numerous other coins (Bitcoin/Litecoin/Dogecoin, etc) but ethereum is new, and the client and interface is different and seems to not be working for me...

**Comment by DJMorgan** [comment]
I also created a contract on the wallet, it took 2 hours, he did not created - with the balance written off funds, after application restart win 10 x64 Wallets 0.9.0 - there is neither account nor the funds that have written off the transaction. how to restore to create a contract of wallet or return the funds?

**Comment by DJMorgan** [comment]
PS: where the developers they will give comments and make corrections?

**Comment by ralibrandi** [comment]
Having the same issue here. Ethereum Wallet v0.9.0 on Windows 10. Nothing in the log to hint at what might be wrong. Transaction is visible on Etherscan but wallet UI still shows it as "Creating" ever since it was created 2 days ago.

**Comment by cross** [comment]
I eventually did find the one contract I created that had made it to the blockchain.  Most of the attempts I'd made at wallet contracts never even prompted me for the gas/value information.  But, one did a few weeks ago, and despite never showing up in the app properly, made it to the blockchain.

After a couple of attempts I was able to import it with the client.  It took _hours_ for it to eventually show up as other than gray ("Importing..."), but hours later after I'd thought it moot, I saw that it had completed.  Hopefully, it will stay there after app restart.

**Comment by arisAlexis** [comment]
having the same issue. tried to import wallet in another client again the same not working.

**Comment by paperbag-zz** [comment]
Anyone knows if this is getting fixed? I have the same issue, after a week of "creating" a wallet, I tried another one, but that is hung up as well.

**Comment by anilbx** [comment]
I am facing same issue. is there anybody who know the reason behind this ? i have tried three times but facing same issue. also block syncing is too slow. although its completed but still contract creation stuck.

**Comment by vess28** [comment]
I am also having this issue. Tried everything to fix it without any luck.

**Comment by CryptoCoding** [comment]
I am having the same issue. 0 of 12 confirmations

**Comment by Uncivilization** [comment]
also creating* great way to support a currency, feels me with confidence that I have x amount in a wallet. That can't sync correctly most times and a wallet I paid for just saying "creating"

**Comment by NlaakStudios** [comment]
Having same issue in v0.9.1 and now v0.9.2 - Been stuck for like 5 days.

**Comment by Uncivilization** [comment]
great I now have missing tokens, but they're on my address but not in the wallet. How do they expect ethereum to go up if little things like this are putting me off.

**Comment by Uncivilization** [comment]
I fixed all my problems using Mist. Sync'd until it stopped 99% closed and restarted the Mist app, let it start loading again. Left it without clicking launch app. Let the forever ending "downloading blockchain" get to over 6mil. Closed the app and opened again, it launched to app fully sync'd.

All transactions etc started to show up. THEN

I Added my missing contract wallet by checking my Eth address with https://etherscan.io then importing the created address of the one I created. 

I'm now sync'd, have contract wallet and see tokens correctly.

If this helps please send Eth 0xf85AED7bE64C131F919EE7CC304B7ce716dD3C00

**Comment by Runner1940** [comment]
errr, same issue here with v0.9.2, the answer above just confused me more.  Anyone please help.

**Comment by Runner1940** [comment]
I also went to put money on the ethereum site and it wanted me to put in my coinbase info, which I did thinking it would pull money from there to put onto the ethereum wallet and instead I just bought more ethereum which just added to my coinbase account, so confused.

**Comment by jbrindle** [comment]
I cannot get either a create or an import like @Uncivilization to work, it just sits whether it is synced or not. I am afraid of transferring anything into the wallet for fear that I will not be able to use it later.
![untitled4](https://user-images.githubusercontent.com/1242794/32130305-2226728c-bb64-11e7-846a-fe29de1eed83.png)

**Comment by Gunna01** [comment]
I've updated to 9.2 and the issue remains. Disappointing so ditching this wallet and highly recommend others do as well. Purchased a hardware wallet and transferred funds out.

**Comment by swen002** [comment]
Same here - gas happily accepted/reduced and that's all the fun - Creating ... few hours now.
Was stupid enough to try twice...
Ethereum Wallet 0.9.2

**Comment by gandra** [comment]
the same issue with Mist ver 0.9.2 on Mac.

Here is the log:
```
INFO [11-10|16:43:01] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/darwin-amd64/go1.9
INFO [11-10|16:43:01] Allocated cache and file handles         database=/Users/gandra/Library/Ethereum/testnet/geth/chaindata cache=1024 handles=1024
INFO [11-10|16:43:04] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Engine: ethash}"
INFO [11-10|16:43:04] Disk storage enabled for ethash caches   dir=/Users/gandra/Library/Ethereum/testnet/geth/ethash count=3
INFO [11-10|16:43:04] Disk storage enabled for ethash DAGs     dir=/Users/gandra/.ethash                              count=2
INFO [11-10|16:43:04] Initialising Ethereum protocol           versions="[63 62]" network=3
INFO [11-10|16:43:04] Loaded most recent local header          number=1729633 hash=5c07ec…a88172 td=2630668671660353
INFO [11-10|16:43:04] Loaded most recent local full block      number=1729633 hash=5c07ec…a88172 td=2630668671660353
INFO [11-10|16:43:04] Loaded most recent local fast block      number=1729633 hash=5c07ec…a88172 td=2630668671660353
WARN [11-10|16:43:04] Failed to journal local transaction      err="no active journal"
WARN [11-10|16:43:04] Failed to journal local transaction      err="no active journal"
INFO [11-10|16:43:04] Loaded local transaction journal         transactions=2 dropped=0
INFO [11-10|16:43:04] Regenerated local transaction journal    transactions=2 accounts=1
WARN [11-10|16:43:04] Blockchain not empty, fast sync disabled 
INFO [11-10|16:43:04] Starting P2P networking 
INFO [11-10|16:43:06] UDP listener up                          self=enode://eb648ac5dee6feea27c0f2644c363ca48f97eebec68fc76e04476c74fc8f0bf89b891338e61fa44119d614d0e0b41e3f2b989ff7f523cfa3d1a4a11a484c649e@[::]:30303
INFO [11-10|16:43:06] RLPx listener up                         self=enode://eb648ac5dee6feea27c0f2644c363ca48f97eebec68fc76e04476c74fc8f0bf89b891338e61fa44119d614d0e0b41e3f2b989ff7f523cfa3d1a4a11a484c649e@[::]:30303
INFO [11-10|16:43:06] IPC endpoint opened: /Users/gandra/Library/Ethereum/geth.ipc 
INFO [11-10|16:44:31] Submitted contract creation              fullhash=0x90fdc0727ce8bc64fb10d2a0f8b8e2decd9b8487cb1a1daac3c7822d14a077ff contract=0x4A97c33AddbAa8E5746AFBEB2404e2fcA3302449
```

**Comment by evertonfraga** [comment]
Hi everyone, hang on, the fix is on its way.

The issue is: when using the light client, it currently does not return the address of the created wallet on `getTransactionReceipt` RPC call. 

This pull request (https://github.com/ethereum/mist/pull/3265) aims to fix that, and from preliminary tests, it works well. Now I'm tweaking the Wallet code to account for this change.

**Comment by bliekp** [comment]
Same problem here. I can see on the network that the contract was created but in the Ethereum Wallet app (Windows 10, x64) it still is 'busy' creating it... restarting the client doesn't help.

No response here from devs doesn't help in growing confidence in this coin...

**Comment by gandra** [comment]
After the days Mist is still in hang mode: https://giphy.com/gifs/26u4ktdvQbRrMeJCE/fullscreen

**Comment by gorshenev** [comment]
Anyone knows if this is getting fixed?

**Comment by gandra** [comment]
Still in hang mode ... `busy` creating: http://www.giphy.com/gifs/26u4lOtRo7c3Qu1LG

**Comment by fv5olFHIsR** [comment]
I have the same problem, TWO wallets STUCK on creating and another contract that is confirmed on etherscan (has over 50 confirmations) i see as pending 0 of 12 confirmations in Ethereum Wallet, this is broken?

**Comment by NimbusToken** [comment]
Same... two contracts stuck while testing.

**Comment by sshumakov** [comment]
As a workaround, I switched to test network, canceled contract creation and switched back to main network.

**Comment by pjdouillard** [comment]
Thx sshumakov, that fixed my issue too of 'Creating...' that never finishes.

**Comment by B-raw** [comment]
Hi all - good news is that the latest version of Mist (0.9.3) fixed this problem immediately for me.

https://github.com/ethereum/mist/releases/tag/v0.9.3

🎉

**Comment by evertonfraga** [comment]
@B-raw correct! 0.9.3 aims to fix that.

**Comment by rafaelcarsetimo** [comment]
0.9.3 Hang here at contract creation.

**Comment by fogonthedowns** [comment]
This is a bad user experience. I'm going to learn go because this is too frustrating

**Comment by bliekp** [comment]
I have switched to a HW-wallet, a Ledger Nano S.
Mist basically *sucks* tbh....

**Comment by fogonthedowns** [comment]
@bliekp I just wish there was documentation on smart contract deployment, in something other than Mist or Javascript. This is such a frustrating experience!

**Comment by temirov** [comment]
In Solo Network, Mist 0.9.3, that fixed it for me:
```
geth attach
> miner.start()
```

**Comment by fogonthedowns** [comment]
@temirov how do you determine when you are on the 'solo network'?

**Comment by temirov** [comment]
It says so in UX after I have selected this network from Develop menu:

<img width="476" alt="mistmenu" src="https://user-images.githubusercontent.com/1078274/33807261-a3591800-dd88-11e7-9021-007d77ab1459.png">

<img width="70" alt="mistprivate" src="https://user-images.githubusercontent.com/1078274/33807240-66ab189a-dd88-11e7-8bf2-caa767892f80.png">

**Comment by mhannigan** [comment]
Same Problem creating wallet contract.  It's been going for two days.  I wish I could at least find a way to cancel it so it wouldn't be so distracting.

**Comment by MungiRumba** [comment]
Yeah, my experience with Mist and Ethereum Wallet has been incredibly difficult.  I agree with bliekp that it needs to be vastly improved to work for your average bear. 

My wallets are also hanging for days instead of being created.  What is the fix?

**Comment by datduong** [comment]
I'm having the same problem. The wallet is taking forever to be created.

**Comment by Boterick** [comment]
Same problem here also, but on Rinkeby Test Network. I have a need to create and test a number of wallets with contracts before committing to live, but now have three stuck at creating... tried restarting on live and Rinkeby, with and without Geth, always synchronising, but no luck. This has all happened since I synced using Geth from command prompt. Mist run on its own prior to that took weeks to sync, but when it did, I created one wallet without incident. Now I cannot create any.

**Comment by burkesquires** [comment]
+1 Having the same issue

**Comment by ismailmayat** [comment]
Same thing here this is with 0.9.3
![capture](https://user-images.githubusercontent.com/1446692/36856763-a8f12746-1d6e-11e8-82cb-972e3e99dd52.PNG)

**Comment by shenzhun** [comment]
I find a way to solve this problem. Go to Developer Tools -> Console.

`Wallets.find().fetch()
`
 it will list the creating wallet contract. 
` Wallets.remove(_id)
` 
the wallet contract will be removed.

![image](https://user-images.githubusercontent.com/2031569/37014355-0705a5da-213b-11e8-93ab-54cc861bec50.png)

**Comment by ismailmayat** [comment]
@shenzhun brilliant that worked for me

**Comment by MungiRumba** [comment]
Where do I find Developer Tools --> Console?

Is this is chrome?  Or Terminal?  I tried Chrome and it didn't seem to
work.

Morgan Robinson
Documentary Film and Television Producer
www.morganrobinson.com
347-524-8489

**Comment by MungiRumba** [comment]
Ah, figured it out.  I just need to go into the keystore, open the coinbase
account with atom, and then edit out the ID value to make it ""  Now the
miner starts up like it should.

Morgan Robinson
Documentary Film and Television Producer
www.morganrobinson.com
347-524-8489

**Comment by shenzhun** [comment]
@MungiRumba Mu it's Chrome, and open the console.

**Comment by seraphjiang** [comment]
@shenzhun remove from console work for me, thanks

**Comment by shenzhun** [comment]
@seraphjiang no biggie. I just shared a gist to remove transactions, wallet contracts & watch contracts in Mist, it is super easy to clean the mess.[https://gist.github.com/shenzhun/61126c3ba8a6dc895594e77f52731afc](url)

**Comment by Boterick** [comment]
Issues all sorted for me now. Hung wallets eventually completed. @shenzhun solution to remove unwanted wallets also since used to clean up in Mist | Develop | Toggle  developer tools | Console.

**Comment by doyajii1** [comment]
@shenzhun solution worked for me too. For osx users console is at Development > Development tools > Ethereum Wallet > Console
