### ISSUE TITLE
Contract Wallet creation hung at "Creating..."

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#3269]
Hi all, this is a canonical issue, to keep our repository organized.

The root cause is: when using the light client, it currently does not return the address of the created wallet on `getTransactionReceipt` RPC call. 

This pull request (https://github.com/ethereum/mist/pull/3265) aims to fix that, and from preliminary tests, it works well. Now I'm tweaking the Wallet code to account for this change.

**Comment by gandra** [comment]
I have the problem with Mist ver 0.9.2 on Mac. Hangs on creating contract.

Here is the log:
```
INFO [11-10|16:43:01] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/darwin-amd64/go1.9 INFO [11-10|16:43:01] Allocated cache and file handles         database=/Users/gandra/Library/Ethereum/testnet/geth/chaindata cache=1024 handles=1024 INFO [11-10|16:43:04] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Engine: ethash}" INFO [11-10|16:43:04] Disk storage enabled for ethash caches   dir=/Users/gandra/Library/Ethereum/testnet/geth/ethash count=3 INFO [11-10|16:43:04] Disk storage enabled for ethash DAGs     dir=/Users/gandra/.ethash                              count=2 INFO [11-10|16:43:04] Initialising Ethereum protocol           versions="[63 62]" network=3 INFO [11-10|16:43:04] Loaded most recent local header          number=1729633 hash=5c07ec…a88172 td=2630668671660353 INFO [11-10|16:43:04] Loaded most recent local full block      number=1729633 hash=5c07ec…a88172 td=2630668671660353 INFO [11-10|16:43:04] Loaded most recent local fast block      number=1729633 hash=5c07ec…a88172 td=2630668671660353 WARN [11-10|16:43:04] Failed to journal local transaction      err="no active journal" WARN [11-10|16:43:04] Failed to journal local transaction      err="no active journal" INFO [11-10|16:43:04] Loaded local transaction journal         transactions=2 dropped=0 INFO [11-10|16:43:04] Regenerated local transaction journal    transactions=2 accounts=1 WARN [11-10|16:43:04] Blockchain not empty, fast sync disabled  INFO [11-10|16:43:04] Starting P2P networking  INFO [11-10|16:43:06] UDP listener up                          self=enode://eb648ac5dee6feea27c0f2644c363ca48f97eebec68fc76e04476c74fc8f0bf89b891338e61fa44119d614d0e0b41e3f2b989ff7f523cfa3d1a4a11a484c649e@[::]:30303 INFO [11-10|16:43:06] RLPx listener up                         self=enode://eb648ac5dee6feea27c0f2644c363ca48f97eebec68fc76e04476c74fc8f0bf89b891338e61fa44119d614d0e0b41e3f2b989ff7f523cfa3d1a4a11a484c649e@[::]:30303 INFO [11-10|16:43:06] IPC endpoint opened: /Users/gandra/Library/Ethereum/geth.ipc  INFO [11-10|16:44:31] Submitted contract creation              fullhash=0x90fdc0727ce8bc64fb10d2a0f8b8e2decd9b8487cb1a1daac3c7822d14a077ff contract=0x4A97c33AddbAa8E5746AFBEB2404e2fcA3302449
```

After the two days Mist is still in hang mode: https://giphy.com/gifs/26u4ktdvQbRrMeJCE/fullscreen

**Comment by stbregeon** [comment]
Hello,

1/is it necessary to create new contracts, or can we get back previously created contracts and administer them?

otherwise can we kill those contracts that are inaccessible to us?

thanks a lot

**Comment by evertonfraga** [comment]
@stbregeon you can import old wallets instead of creating new ones.

**Comment by dcnl1980** [comment]
Not only hangs on wallet, also tokens are not visable.

**Comment by stbregeon** [comment]
right now, i can watch my tokens (deployed with light client) on my wallet but I can't administrate them

**Comment by jenniferdejonge** [comment]
Am I right that it has not been fixed yet?
Or can someone tell me how to fix it?
This not creating a wallet and so also net be able to make any acts with the ethereum

**Comment by evertonfraga** [comment]
@jenniferdejonge it's not fixed yet. It'll be on the next version, 0.9.3.
you can grab the address of your created wallet (on etherscan, for instance), and import it using ethereum wallet.

**Comment by jenniferdejonge** [comment]
I just took a look at etherscan but can’t seem to find a way to find my created wallet.
Please run me true?
When do you expect 0.9.3 will be there?

**Comment by evertonfraga** [comment]
1. Paste your account address at http://etherscan.io/ search bar
2. Se on the transaction list if there are any Contract Creation link
3. Follow the link and grab its address
4. Head back to ethereum wallet, "Add wallet contract", import (3rd option)

I'm aiming for a new release later this week.

**Comment by jenniferdejonge** [comment]
Thanks for all the help.
I have followed your directions.

For now the wallet I wanted to create is still running.
The importing does not show anything also the circle doe not give all the colors as the first not creating wallet does.

Jenn

**Comment by evertonfraga** [comment]
Ready for testing: 
Mist: #3265  
Wallet: https://github.com/ethereum/meteor-dapp-wallet/pull/427

You have to run both of these branches. release ETA: beginning of the next week

**Comment by litebito** [comment]
Hi,

same issue here, but this also seems to prevent me from making any other transaction:
- I've 4 wallets, in the client
- and at least 1 wallet contract attached to each of them
- most of my funds are in the wallet contract, not the wallet. 
- I've tried MEW (never used it before) but that does not show the spendable balance in my wallet contracts

so as long as this issue blocks me, I cannot move ETH into my wallets, nor make payments from wallet contracts. So I'm stuck, unable to process urgent payments (and lose money  in the process by not being able to act)

**_Is there not any other option than this ethereum client for those who have "wallet contracts" ?_**

L.

**Comment by evertonfraga** [comment]
@litebito if you are savvy enough, you can use Remix IDE (https://remix.ethereum.org) along with the wallet's source code to execute functions on your wallet contract.

https://github.com/ethereum/meteor-dapp-wallet/blob/develop/Wallet.sol

Let me know if you need any further information.

**Comment by litebito** [comment]
I'm afraid that seems to be a little bit out of my league ...
so I'm understand correctly, there is no other wallet supporting wallet contracts in a direct usable way?

**Comment by 0-0-0-** [comment]
Thanks! Improving the ecosystem one update at a time!

**Comment by evertonfraga** [comment]
Guys, 0.9.3 is out: https://github.com/ethereum/mist/releases/tag/v0.9.3

Bug is fixed. should you have any other behavior, please open another issue.

**Comment by stbregeon** [comment]
@evertonfraga 
thank yyou very much. I just need à clarification : how can I recover contracts which have been created under version 0.9.2. with sync litgt client, to administrate them?
(I can see and add them as a user but i can't administrate them with the wallet ethereum)
or, Does It necessary I create some news?

**Comment by merket** [comment]
@evertonfraga I am using, 0.9.3 but I have the same exact problem with all my contracts. They have been stuck on "creating" for a month now. What do I have to do?

**Comment by takifugu** [comment]
@evertonfraga - I am using 0.9.3 on mac and am still having the problem.  Wallet creation is stuck.  I see nothing in the logs.  I tried creating 3 and all 3 are stuck.

**Comment by evertonfraga** [comment]
@stbregeon it's not needed to create a new one. Please try the Import Wallet feature. Should this fail, try this: https://gist.github.com/evertonfraga/5791b2d698ab1d762e1f357c92ea484a

**Comment by evertonfraga** [comment]
@merket @takifugu thanks for reporting. 

Can you confirm if you have enough peers you're downloading blocks from? That initial bug was fixed, but it will only actually work if you are successfully connected to other peers.

**Comment by takifugu** [comment]
After switching to the test network…

All pending disappeared.   I then attempted again and it brought up the full window to add the contract.   I believe it may be working now after I got rid of the old pendings.

Connected to 8 peers.

--Anthony

**Comment by kspeedrent** [comment]
I am also having trouble deploying contracts on Rinkeby.  The first contract I deployed (Token) was successful but every attempt after that has been stuck.  I've tried increasing my gas max but that's had no effect. Is there a minimum number of peers to be successful?

**Comment by asierarranz** [comment]
Same here, stuck creating 3 contracts. Also stuck in "Creating..." when creating a Wallet Contract.
Windows 10, installed yesterday. Last version (0.9.3)

**Comment by GmWM** [comment]
Still not working. I'm stuck with 2 contracts...

**Comment by 0-0-0-** [comment]
This requires a bit of patience but deleting the folder with the current block chain state and then choosing the Light Synch option appears to work. It takes a bit of time but eventually it will peer.
Dont worry if you think its not doing anything for while its working. If you get bored then restart the client and let it do its thing. Light synch does not bring up a progress bar or countdown the blocks like the regular synch. It will eventually pick up between 1 and 5 peers the longer you leave it connected the more peers it picks up. Bonus is no more drive hogging chain state files. Over all once its caught up it will stay synched.
