### ISSUE TITLE
Sent 400€ worth of ether from Bitstamp to the Cryptopia exchange, ether not credited

### ISSUE THREAD

**Issue by RPBMedia** [ethereum/mist#3387]
Hello, maybe you can help me understand this and provide me with potential solutions.

I sent 1.01534527 ETH to this address: 0x2a829f914b8dfb93dd290b5225ea58b311638f6d

Here is the transaction id: 0xe1800bfa226e2ab85706f63642856db130bd718ea947615838376cab43cacf65

Those funds were never credited in my Cryptopia account and are not available on Bitstamp either.

On etherscan this transaction appears as "Internal transaction". Now, I am aware that internal transactions are not "real" transactions as they are not included in the block chain.

My question is: Given that I have transfered ethereum from Bitstamp to Cryptopia before with no issues, why was this transaction categorized as "Internal", and what can I do to have my Ether back?

Thank you so much

**Comment by tobiv** [comment]
According to etherscan, the address you gave has 1.01534527 Ether, which is the amount on the transaction. Looks like it's an issue with Cryptopia.

Note: this has nothing to do with `mist`, please direct similar questions to the appropriate place in the future.

**Comment by samomalo** [comment]
I have the same problem. How did you sort it out?
I've created a support ticket, but no answer yet...

**Comment by michaeb** [comment]
Hi, did this ever get resolved? I'm having the same problem.

**Comment by samomalo** [comment]
It was resolved for this guy:
https://bitcointalk.org/index.php?topic=2519580.0
...so I'm hoping for positive outcome.

I'm still waiting for answer. Due to large amount of tickets average response time is 12 days :((((

**Comment by michaeb** [comment]
Thanks for getting back to me, lets hope they get it resolved for both of us too. I'll let you know if I have any luck!

**Comment by alexvandesande** [comment]
This is not a Mist issue, it seems.

I am closing this issue due to inactivity. **Please feel free** to reopen should you still have some considerations about it.

**Comment by thanksmia** [comment]
I also have send eth to cryptopia after 6 hours and more than 1000 confirmations still not showing on cryptopia adresses matches wtf is this?!
