### ISSUE TITLE
Ethereum never arrived to my Gatehub wallet

### ISSUE THREAD

**Issue by MarioMunnoz** [ethereum/mist#3477]
Hi,

I have sent Ethereum from Coinbase to my Gatehub Wallet wich is the perfect address. I have checked at Etherscan and the transaction was correctly finished. The point is that i've sent a bunch of emails to Gatehub and no answer. What can i do?.

this is the transaction at Etherscan.

https://etherscan.io/tx/0xcdb83284af5e76626cd64b84fbd95b9d23a966cbe1fa217bfbc2562e79ac2594

<img width="1440" alt="screenshot" src="https://user-images.githubusercontent.com/26086380/34318872-22f81bd0-e7d2-11e7-9643-84e1d3b946d6.png">

This is my ethwallet

<img width="990" alt="screenshot2" src="https://user-images.githubusercontent.com/26086380/34318879-49883262-e7d2-11e7-9e95-8f15f5588841.png">

Any help please? 

They don't answer and i think everything is correct so how can i report this? it's been two days and nothing.

Thank you

**Comment by tickerey** [comment]
Hey dude, same shit.
Nothing is arrived, no support...it just terrible 
<img width="732" alt="bildschirmfoto 2017-12-23 um 01 38 46" src="https://user-images.githubusercontent.com/224665/34319101-4e2d7b04-e7d9-11e7-8b67-f23a623e8d44.png">

**Comment by p069128** [comment]
Same boat.  Bitstamp to Bithumb.  Transactions all on Etherscan but no money in my wallet.  Contacted Bithumb and no response, just keep waiting for Blockchain to clear.  I don’t think it’s a Blockchain issue.  Don’t know if it’s Bitstamp causing these issues by using smart contracts that the rest of the exchanges are not prepared or it’s all Bithumb.
0x30fc2c0a16bf8ba67c50e920bf6fd47edd270b6bf40662a8c080cd754f300a2e
Anyone confirm this transaction with me.  From what little I understand it’s has been confirmed?  This is my wallet address in TX ID

**Comment by michaeb** [comment]
Hi! Did this ever get resolved for you? Same thing has happened to me.

**Comment by p069128** [comment]
Not yet, still working on it, may take weeks.  Some wallets cannot handle smart contracts.  ETH should not be on exchanges

**Comment by imghasemi** [comment]
Same problem, any update yet?

**Comment by p069128** [comment]
Last message said be patient and give it 2 to 3 weeks.  No funds yet, but I’m optimistic.  I have been stuck in ETH for 2 weeks hoping it does not crash

**Comment by p069128** [comment]
I can also see my ETH in my wallet at Etherscan.io

**Comment by p069128** [comment]
Not yet.  Told me to give it 2 to 3 weeks.  It’s been 2 weeks

**Comment by hanley24** [comment]
The same thing just happened to me. Who did you contact to tell them about the issue? I can't find any phone numbers or email addresses on the GateHub site.

**Comment by p069128** [comment]
This is happening to me on Bithumb, sorry for the confusion.  I do think I read somewhere about other sites charging a 10% fee to manually deposit ETH smart contract.

I kind of blame Bitstamp for screwing all the other exchanges up

**Comment by telecommike** [comment]
hi i have also sent ethereium from coinbase to gatehub with success according to etherscan but nothing is showing , anyone on here have success in the end , is so how long did it take

**Comment by 0marcel0** [comment]
I have the same problem with Huobi, Okex and Bithumb. I have sent ETH to these platforms from my Bitstamp account. Anyone who solved the problem till now?

**Comment by vexxedd** [comment]
Just made a transaction today (0.5 eth) to GateHub wallet. Trust was enabled before that. Coins arrived to wallet in about 5 hours.
Be sure your Trust is enabled and you accept it on your email.

**Comment by MarioMunnoz** [comment]
Yes, For me was solved too. But they took like a month to trust my wallet and during that time i was trying to find solutions to my problem and all i got was bad reviews and bad comments about GateHub. I've found they are just 13 empolyees and they are saturated because they have millions of users. My advice to everyone is to avoid Gatehub, in case you are waiting a response just be patient and as soon as they trust your wallets take your money from their services.

**Comment by telecommike** [comment]
thats good to hear you finally got your money . you seem to know your way around gateub more than me at the moment . really need some help . i  use gatehub and coinbase.  done my first transaction and bought ETH on coinbase and sent it to gateub  but its still not showing after 5 days ... it maybe because i have 19.99 ripple in my wallet and 1 in my ETH gateway which has trust enabled .. i think i need over 20xrp in my main wallet and over 5 in my ETH gateway , does you know if this is correct , really appreciate any help to get me started and recover my ETH  wherever it may be at the moment , i need to by small amount of XRP i think to make my wallet work and receive my ETH . any chance you can send/sell me any and i can pay on paypal before you send  .. any help would be really be appreciated thank for Mike UK , unless you know a way i can add some XRP to my wallet via another platform

**Comment by telecommike** [comment]
trust is enabled but i never got an email . not sure i have enough xrp in gateway or ripple wallet . 19.9 in ripple and .5 in ETH gateway trust

**Comment by vexxedd** [comment]
Well as for me it was 20 XPR in ripple wallet from the start, then I enabled trust on BTC and ETH (confirm on email) and made like 0.05 BTC transtaction. Took about 5 hours to reach wallet as well. Did few transactions inside GateHub like BTC to XPR/ETH. Also send from GateHub to Bittrex some ETH, was about 10 mins. And 2 weeks later did 0.5 ETH transaction to GateHub, was about 5 hours as well.
So this was my steps. Not sure what is wrong.

**Comment by MarioMunnoz** [comment]
Telecommike, you must enable your wallet. You have to trust all of them in advanced settings, it last few weeks too...... they have to accept your request. You have to click on the left menu item Home. And find connect Gateway and find your ethereum wallet or the crypto which you want to trust and click on trust or confirm. If you don't have Connect Gateway item you have to click on wallets and at the bottom you'll find advanced. Click on there and you will see trust button on every wallet. After you have trusted all in advanced you have to trust them in the gateway too and after a couple of weeks you will have the wallet available and your ethereums. Try to push via email too the support because they are so slow but finally after you have your wallets enabled you'll get your coins.

I hope you solve it.

**Comment by paintedrough** [comment]
Same here bitstamp to bithumb and waiting for it for over a month by now. Even said that it might not be recovered:

"As regards your enquiry, we are afraid this issue may take a much longer time than you may expect it to be due to the fact that your deposit was made through multi-sig account. Moreover, there is a chance that your deposit might not be retrieved as a rsult."

**Comment by p069128** [comment]
Ouch.  They should just reverse the transfer.  I won’t go quietly.  They know have 65,000 USA locked up.  It shows on the Blockchain

**Comment by paintedrough** [comment]
We can keep writing them but not much else to do. I called several times as well and the support staff does not even know what a private key is. Should be so easy...

**Comment by p069128** [comment]
I may have to fly over there.  Luckily I’m also in the USAF and can find a hop over to S Korea.

**Comment by paintedrough** [comment]
Sounds like a plan, keep me posted ;)

**Comment by 0marcel0** [comment]
I opened a topic here related to the Bithumb ETH deposit issue: https://github.com/ethereum/mist/issues/3530

**Comment by telecommike** [comment]
finally sorted my gatehub problem , once i had enough ripple in my wallet i.e. 20 and  5 for the ETH gateway and then enabled trust . my etherium finally  came through 2 days later . i noticed on etherscan it was sitting in gatehubs hot wallet address until i had set up my account properly . no help from gatehub though

**Comment by shubham62** [comment]
@telecommike  how did u came to know that ETH coins were there in gatehubs hot wallet address

**Comment by shubham62** [comment]
I transferred my ethereum coins from one wallet to gatehub's wallet and coins never came 
after reading above I found that you have to connect a gateway, and after doing it still no sign of coins in my gatehub's wallet, its more than 5hrs 
please help.

**Comment by telecommike** [comment]
hi how many ripple do you hold in total in main wallet , it will need to be more than 25 , once you connect gateway you will need to go to advance icon in bottom right hand corner to enable trust , once i done all this ETH came through but still took a couple of days , look at your transaction on etherscan using your address line of where you sent ETH , it showed it going from my address and out to gatehubs hot wallet Ethereum hot wallet: 0x1595c383f52e474b28b5e6b4b8f72e92c1461474

**Comment by shubham62** [comment]
@telecommike there are enough ripples in my wallet and as per your instructions I had done all the trust thing now  but during "SET TRUST" it was asking ripple address and currency what it is actually ??
and I checked on etherscan out address was the my wallet address 
take look here are screenshots
![crop wallet address](https://user-images.githubusercontent.com/11058598/34914568-1a1c8a76-f93b-11e7-803b-37cb296627ee.png)
![screenshot from 2018-01-14 14-52-12](https://user-images.githubusercontent.com/11058598/34914569-21f94554-f93b-11e7-97df-ffb5e71015bf.png)

**Comment by telecommike** [comment]
on your transaction above . click on the to hash and see what it show you should show another transaction , ripple address and currency didn't seem to matter , i tried gatehubs public xrp address which it took but didn't seem to make any difference or go through , did it say trust was successful on your eth gateway?

**Comment by shubham62** [comment]
@telecommike  yeah trust was set successfully, does gatehub sends you confirmation email when you connect to gateway ? 
it is showing only one transaction 
![etherscan](https://user-images.githubusercontent.com/11058598/34914774-54e88494-f93f-11e7-81d2-9442f8e0d153.png)

**Comment by AndreiPL** [comment]
exactly the same problem. I sent 0.2 Etner from the main gatehub.net wallet to my second wallet at the gatehub.net
etherscan transaction is displayed correctly, and on wallet still 0. 
at the same time with the same wallet, I sent the etherium to my wallet at the blockchain.info, the transaction went for 1 minute.
using etherscan I checked the condition of both my wallets, and found out that in both cases the balance is not true.
I think that GateHub Fifth confuses the numbers of wallets or something like that.
in any case, I can not manage my money, and with this I need to do something.
in plans to withdraw all money from GateHub and never to return to them, but you need to somehow return my 0.2 eth

**Comment by shubham62** [comment]
@AndreiPL lets wait and watch, there is nothing else we can do
i think i lost my money.

**Comment by AndreiPL** [comment]
https://www.facebook.com/GateHubNet
https://support.gatehub.net/hc/en-us/requests/new
https://www.gatehub.net/gateways/fifth/

**Comment by AndreiPL** [comment]
https://twitter.com/gatehub

**Comment by AndreiPL** [comment]
fifth@gatehub.net

**Comment by shubham62** [comment]
bro does gatehub charge us some ripple fee when we transfer ethereum to gatehub 
my ripple balance just went low by 0.0098 xrp ?????

**Comment by AndreiPL** [comment]
Incoming and internal transactions ETH without commission
https://wallet.gatehub.net/#/help/about/

**Comment by AndreiPL** [comment]
![105](https://user-images.githubusercontent.com/35140404/34920239-915c2aac-f980-11e7-9434-1c637e146d35.png)

**Comment by shubham62** [comment]
what is "ETH Ripple Fee" then ??

**Comment by AndreiPL** [comment]
maybe its the problem. I think they use XRP for internal translations.

**Comment by AndreiPL** [comment]
no. The problem is in the wallet. 
I send 0.01 ETH from blockchain.info to problem wallet, and it Also not shown on gatehub wallet.
![106](https://user-images.githubusercontent.com/35140404/34921001-d3739860-f98c-11e7-8fdc-9b52768adb1e.png)

**Comment by AndreiPL** [comment]
how many wallets do you have on gatehub? 
you sent ETH to the main wallet or to the second?

**Comment by AndreiPL** [comment]
gatehub.net it's a fraudulent site!

**Comment by shubham62** [comment]
@AndreiPL bro i have only one wallet which is the main one
how can u say that its a fraud site ??
it is listed on ripple's official site as the main wallet which they recommend to use 
![gatehub](https://user-images.githubusercontent.com/11058598/34951992-227e92dc-fa3e-11e7-89a2-0a4b6b19c2c7.png)

**Comment by AndreiPL** [comment]
@shubham62 no.
![111](https://user-images.githubusercontent.com/35140404/34952567-3f7028d2-fa2b-11e7-886a-0e826c15084f.png)

**Comment by AndreiPL** [comment]
@shubham62   I poked a couple of times on the button to open the gateway. I did this before, but just in case repeated.  will observe further.
5 days ago I also sent 150 dollars through Swift to my bank account from the account gatehub.net
I suspect that I will not see this money, at least in the near future.

**Comment by telecommike** [comment]
Hi i decide to post a video on youtube once i worked out mine , hopefully it might help you
https://www.youtube.com/watch?v=zlcudWjSWaA&t=22s MIKE

**Comment by Kat9601** [comment]
Hello to everyone. 
I do have the same issue with ETH tranfer from Coinbase. Firstly, Not knowing about the minimum for transfer I sent less than 0.05, but yesterday I sent much more with gateway connected for ETH. Hovewer, nothing yet. So I tried again to set trust in advanced settings- HOPE THAT WORKS!
The curiosity is that I have operated with ETH but within GATEHUB by exchanging BTC for ETH and everything was fine...
The EtherScan says the operation was successful- both of'em. 
The wallet address is correct for both transactions. I also checked the detailes where the final destination is my ETH wallet- not hot wallet.

Anyone has an idea what else might be a problem? considering that I have ripple on my wallet- so the wallet is active.

**Comment by shubham62** [comment]
hello all received my Ethereum, approximately 6 days later .
Thank You all for your help !!

**Comment by anjanal** [comment]
I received my ETH, Issue solved., First check if the gatehub ETH wallet address has send your ETH to another contracted wallet(gatehub main ETH hot wallet).. If(your ETH was transfer to that) you will received your ETH on most probably within 2 days. altogether it has been 9 days for me. If anyone exceeded 15 days please comment ,that i have other tips for contacting them.....

**Comment by evertonfraga** [comment]
As this is off-topic, i'll close this issue. But feel free to keep going with the discussion. Good luck!

**Comment by luk2220** [comment]
Hai...

**Comment by luk2220** [comment]
Hai..
I deposit dash to gatehub on 1 feb but until now still not show in my wallet? I checked with explorer dash..the transaction was successfull.... what to do? Any suggestion?

**Comment by kyleatx** [comment]
kat9601 I did the same as you 
(deposit less than .052!  Did you ever get the .05 ETH even though it was lower than min.?

**Comment by luk2220** [comment]
Hai
How ur transaction?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: kyleatx <notifications@github.com> Date: 08/02/2018  11:58 p.m.  (GMT+08:00) To: ethereum/mist <mist@noreply.github.com> Cc: luk2220 <lukman.884@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [ethereum/mist] Ethereum never arrived to my Gatehub wallet (#3477) 
kat9601 I did the same as you

(deposit less than .052!  Did you ever get the .05 ETH even though it was lower than min.?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kyleatx in #3477: kat9601 I did the same as you \r\n(deposit less than .052!  Did you ever get the .05 ETH even though it was lower than min.?"}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/3477#issuecomment-364157026"}}}

**Comment by p069128** [comment]
All good. I got paid on 1 Feb.  Took them 45 days but they did it

**Comment by kyleatx** [comment]
I sent .05 from my etherwallet to gatehub wallet.

**Comment by kyleatx** [comment]
p069128,

So even though you send below threshold of .05 eth you still got it?  Why do they set minimums any way?

**Comment by p069128** [comment]
No, I was at 1.00 Eth min

**Comment by dogan1988** [comment]
Same for me, I send Dash to my GateHub wallet 2 weeks ago. Still haven't recieved anything. They don't respond to any support requests. I feel like I have been robbed!

**Comment by luk2220** [comment]
Me..today credit to my wallet...yey


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: dogan1988 <notifications@github.com> Date: 15/02/2018  2:56 a.m.  (GMT+08:00) To: ethereum/mist <mist@noreply.github.com> Cc: luk2220 <lukman.884@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [ethereum/mist] Ethereum never arrived to my Gatehub wallet (#3477) 
Same for me, I send Dash to my GateHub wallet 2 weeks ago. Still haven't recieved anything. They don't respond to any support requests. I feel like I have been robbed!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dogan1988 in #3477: Same for me, I send Dash to my GateHub wallet 2 weeks ago. Still haven't recieved anything. They don't respond to any support requests. I feel like I have been robbed! "}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/3477#issuecomment-365708565"}}}
