### ISSUE TITLE
Transaction stuck in progress

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#389]
Ok so after my first issue of thinking I'd lost my Ether I now came across a new problem. I have tried to transfer my remaining ether in my account to my wallet and I also tried to donate some Ether to receive my unicorn (sounds strange I know). The 2 transactions have been sat at the bottom of my window since yesterday and both still say 0 of 12 confirmations so the transactions aren't being processed, why would this be?

Also while I'm on here I might as well mention that when I sign in to Eth 1.2.1 (C++) using my master password it allows me to login however the 'unlocking' window doesn't disappear, it remains there the whole time I'm logged in and if I try and close it down it shuts the whole Ethereum Wallet down.

Thanks for any help on this!

**Comment by bas-vk** [comment]
Could you explain a bit more how you are using the wallet? Did you start an eth instance manually and then the wallet?

Could you post the transaction hashes? Click on the transaction in the overview, a new window will open and you should see the hash.

**Comment by bikerboy4489** [comment]
I'm a bit of a noob on all this so I'm not quiet sure I understand the question. I downloaded Ethereum wallet 0.3.7 when that was released which is when I set up my wallet after being advised to do so from a colleague. Since then I have purchased a little more Ether which was placed in my wallet.

I am now running version 0.5.2 and simply use it to store my Ether. I have 34.99 Ether currently stored in my wallet here 0x46e5ee7101B6CD1348dFE5235bB2c67faEe7bFfE and have a further 25.73 located in my account 0x0028653950a9F5104D30e1978ab80648AA0f5213. I am trying to transfer the 25.73 to my wallet however it isn't showing as a successful transaction.

If I click on the transaction ID it simply shows me a link to http://etherscan.io/tx/0x9ab366c47c9af2763ea0dad3401d8f04e7f989b00eeab5c062f8577b57b612e9 which shows 'Unable to locate Transaction entry'. This also occurs on the 2nd transaction which I did to receive a unicorn, transaction http://etherscan.io/tx/0x52a4c11bd9a9626e16d7e149006fee27b167291f2c9fcf298d28dd4b567cc470

So it appears that since I did the latest update it will no longer allow me to make any transactions.

I hope this helps you understand my problem a little more.

**Comment by poinerdy** [comment]
Did this get resolved?

**Comment by greensquid** [comment]
I'm having the same issue (Mist 0.5.1).

**Comment by frozeman** [comment]
@bas-vk @fjl it seems like the node doesn't connect and therefore doesn't relay the transactions. Can you have a look?

**Comment by bikerboy4489** [comment]
Hi, this problem was never resolved it only got worse. I opened a new issue which explains that the Ethereum has disappeared completely which is EXTREMELY frustrating. Take a look at the new issue here, https://github.com/ethereum/mist/issues/476.

Any help would be greatly appreciated.

**Comment by cassiopaia** [comment]
i'm facing same problems on `OSX Yosemite 10.10.5`

**Comment by adamduren** [comment]
I had the same issue with `Mist 0.7.4` connected to `geth 1.4.3` (instead of running it's internal node). I tried sending the transaction 4 times and they all disappeared eventually from Mist after minutes of 0 confirmations. I tried raising the fee although I didn't think it was related.

**Reverting to `geth 1.3.6` solved the problem immediately.** Not sure if this will work for everyone but it helped me.

**Comment by cassiopaia** [comment]
recent wallet version solved issue for me ...

**Comment by Kurtbe** [comment]
I have exactly the same issue and have no clue... Running EW app 0.7.4. under Win 10.
My ETH's don't want to move. Confirmations do not happen and after time the transaction just dissapears. How to setup geth? To find out if 1.3.6 would be a solution.

**Comment by Kurtbe** [comment]
Oops, apparently, I am running 1.3.6...

**Comment by Kurtbe** [comment]
I contacted The DAO forum and they recommended using 0.6.2. That did the trick.
So maybe it is a solution for you to... (I hope)
Greets, Kurt

**Comment by bikerboy4489** [comment]
Thanks @kurtbe I'll give it a go

James.

**Comment by Gondee** [comment]
Can anyone confirm 0.6.2 solves the issue? 

Best,
Josh

**Comment by bikerboy4489** [comment]
Hi Josh,

I'm still stuck with this situation. When I enter my master password it says unlocking, in the background it opens the accounts so the login definitely works but the the 'unlocking' window doesn't disappear so it won't download the blocks so I can't make a transaction to remove my Ether! So frustrating, it's like having money in your bank that you can't touch it...

This needs to be fixed!

**Comment by Kurtbe** [comment]
Hi Josh,  It did for me.

 

Met vriendelijke groeten,

 

Kurt

 

P  Denk even aan het milieu voor je deze mail afdrukt

Fortunam suam quisque parat.

**Comment by Gondee** [comment]
@Kurtbe @bikerboy4489 Thanks guys, I'm going to test this with the other version tonight. 

On my end my client becomes unsynced and any transaction attempts never get confirmed. As a quick workout for those stuck with this issue, I have seen that transferring the ETH immediately upon wallet open with the highest transaction fee works most of the time. 

Best,
Joshua

**Comment by yunesj** [comment]
I'm having this issue. Transactions disappear from under "Latest Transactions," and there is no record of the transaction on any block explorers.

I'm using Mist version 0.7.5 on Geth 1.4.7 on OS X 10.10.5. It's a fresh install. My account json files were copy-pasted from a cpp-ethereum installation on another machine. My blockchain is / was synced.

@Gondee's workaround worked for me: following his method, a new transaction went through, the previous transaction that formerly disappeared went through, but an even older transaction did _not_ go through.

Because I can't tell if the disappeared transactions will eventually be processed, I cannot decide if I should send a new transaction in its place. Any advice?

**Comment by emizzle** [comment]
I've had the same issue on OSX 10.11.3 with Mist 0.7.3 (and geth 1.3.6). Had a transaction just sitting with "0 of 12 confirmations" and the transaction did not existing on the blockchain, and also I noticed my wallet was falling behind the synced blocks essentially never being updated with the current block (even though when attaching geth shows the blocks are synced properly). I just upgraded to Mist 0.7.5 (with geth 1.4.7-stable) and I've noticed the wallet UI syncing issue has been fixed (ie it doesn't fall behind the block sync), and the failed transaction appeared for a while (with "0 of 12 confirmations") and then it just disappeared and is still not registered on the block (http://etherscan.io/tx/0xd4659ab9252bdba85443ae4329b76ca25fb0d412452821abaa645e8df861bd4d). Additionally, my ether balance has not been restored to pre-transaction amount. The transaction was only 0.5ETH so I'm not concerned but it doesn't invoke much confidence in sending larger amounts. 

Any ideas on what may have happened to the transaction or how to rectify the balance?

**Comment by greensquid** [comment]
After upgrading to 0.7.5 (Linux 64bits) and redownloading the entire blockchain, the stuck transaction was removed from from the history and I'm now able to send ethers. Thanks for fixing that issue!

**Comment by digidan** [comment]
So I'm having the same issue running the latest version.  I keep trying to send but it never shows up on the blockchain and eventually disappears from latest transactions.  Any ideas?  I'm on OSX El Capitan latest release.

**Comment by cellard0or** [comment]
The same still happens to me with Mist 0.8.1 and parity 1.2.2. This kept me from voting on the fork on carbonvote already, now it is keeping me from handling my ETC. Any help is very much appreciated.

**Comment by keech** [comment]
related issue?
https://github.com/ethereum/go-ethereum/issues/2950

**Comment by AmorimJ** [comment]
I have 5 transactions with a lot of confirmations, like 1000+ confirmations, why those don't end??

Best regards,
João Amorim

**Comment by Cryptocurrbit** [comment]
Can anyone help me out I have an issue with a transaction stuck on Ethereum  block-chain..for over a week now..
I think my transaction settings was set to zero mining fees for some dang reason so is there  any way to get this back?

**Comment by AugustoEst** [comment]
I'm still having this issue in 2018. How is it possible to have a wallet that doesn't allow you send ETH?
