### ISSUE TITLE
Synchonization issue

### ISSUE THREAD

**Issue by apobekiaris** [ethereum/mist#397]
When i start the wallet I get 

![image](https://cloud.githubusercontent.com/assets/159464/13903799/ed3c477a-eebb-11e5-8119-002b331f260b.png)

and i do use time servers

![image](https://cloud.githubusercontent.com/assets/159464/13903801/15efde3e-eebc-11e5-8082-bf7f4f384fcc.png)

**Comment by hiddentao** [comment]
What version of Windows are you running?

**Comment by bas-vk** [comment]
Apperantly Windows will only synchronize once a week ([source](http://www.thewindowsclub.com/change-internet-time-update-interval-windows)). In most cases this will be sufficient but in your case it might not. Could you manually synchronize the time? I assume if you select a different ntp server Windows will re-synchronize.

**Comment by frozeman** [comment]
The upcoming mist version will only look if the time is set to automatically and not compare times anymore. This should fix this issue.

**Comment by faruqluqman** [comment]
I've downloaded and began using Ethereum-Wallet-win64-0-5-2. For the first use, "Ethereum node needs to sync" was complete and I could run the app.

Since restarting, I have had a problem of "Ethereum node needs to sync" stagnating around downloading block 400,000+.

Read some forums/discussions that the PC time synchronization could be a problem and should be synced with a world server time.

So I installed Atomic Clock Sync v3.5 (http://www.worldtimeserver.com/atomic-clock/) and set it to synchronize my PC clock (Lenovo Ideapad 100 running Windows 10 Pro) every hour while "Set Time Automatically" under "Settings > Date & time" of the PC is put as off (since I want the Atomic Clock to be setting the PC time).

Now the "Ethereum node needs to sync" stagnates around downloading block 500,000+ even after various attempts and restarts.

Would really appreciate if anyone can guide me on overcoming this issue I am still facing.

**Comment by tageeboy** [comment]
I have windows 10 and am using the default auto sync time servers. Same issue here since installing latest version.

**Comment by solidstructure** [comment]
The following helped me get rid of the above error. Now I am currently trying to sync with the ethereum node. 
Go to (windows 10):
Date and Time Settings --> additional date, time & regional settings --> set the time and date --> internet time tab --> change settings --> changed server to time-nw.nist.gov and then update

**Comment by tageeboy** [comment]
I tried to do a force time update and it still failed. I went ahead and rolled back to previous version. Thanks for the info solid, here is the command line to force sync.

w32tm /resync is to force a time resync but needs to be run in elevated CMD

**Comment by woftor** [comment]
Have the same issue, while my PC's time is perfectly synced automatically. It even reports this after I manually sync. Windows 10 and Myst 0.7.2.

**Comment by woftor** [comment]
This bug is still there in 0.7.3. My Windows 10 machine is 100% correct  timesynced, but it will allways throws this error.

**Comment by woftor** [comment]
Still there in 0.7.4.
Already deleted the blockchain, no change.

**Comment by luclu** [comment]
@woftor could you kindly give me the output of this commandline command?
```
reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time
```

**Comment by luclu** [comment]
For **those interested** in a **long and technical explanation** I will try to give you some technical background on this issue.

---

Time-sychronisation is important as the underlaying network protocol [devp2p](https://github.com/ethereum/wiki/wiki/%C3%90%CE%9EVp2p-Wire-Protocol) depends on a shared timebase for its correct functionality.

[NTP (Network Time Protocol)](https://en.wikipedia.org/wiki/Network_Time_Protocol) is the mean by which Operation Systems can synchronize their time to the one of some (public) NTP server.

Sometime NTP is disabled for some reason or its configuration broken thus the ethereum-client ([geth](https://github.com/ethereum/go-ethereum) as default) will connect and immidiately drop its peers thus not synchronize the blockchain.

To give some feedback to the often clueless user Mist leverages the node module [os-timesync](https://github.com/fjl/os-timesync) in its [main.js](https://github.com/ethereum/mist/blob/develop/main.js#L14)-file.

On [line 236](https://github.com/ethereum/mist/blob/develop/main.js#L236) it will check for the enabled NTP functionality and will show that error-dialog if the check fails:

```
    timesync.checkEnabled(function (err, enabled) {
        if(!enabled) {
            dialog.showMessageBox({
                type: "warning",
                buttons: ['OK'],
                message: global.i18n.t('mist.errors.timeSync.title'),
            }, function(){
            });
        }
    });
```

This will evoke the [following routine](https://github.com/fjl/os-timesync/blob/master/index.js#L26) on windows OS:
```
function checkWindows(cb) {
    var args = ["query", "HKLM\\SYSTEM\\CurrentControlSet\\Services\\W32Time", "/v", "Start"];
    childProcess.execFile("reg", args, function (err, stdout) {
        cb(err, /REG_DWORD\s+0x3/.test(stdout));
    });
}
```
which checks the output of the (commandline) command:
```
reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time
```
If NTP is enabled this will output among others:
```
REG_DWORD    0x3
```
if it is deactivated:
```
REG_DWORD    0x4
```

This basically means there could be two reasons for a false error:
 - this dialog could still falsely appear because the synchronization will take time to happen (a reboot could be appropiate for this change to reflect.)
 - that check-command could not working on some OS-versions and needs an adjustment

**Comment by frozeman** [comment]
@fjl maybe some improvements on you package are necessary? https://www.npmjs.com/package/os-timesync

**Comment by woftor** [comment]
> @woftor could you kindly give me the output of this commandline command?
> reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time
    Start    REG_DWORD    0x2
    DisplayName    REG_SZ    Windows Time
    ErrorControl    REG_DWORD    0x1
    ImagePath    REG_EXPAND_SZ    %SystemRoot%\system32\svchost.exe -k LocalService
    Type    REG_DWORD    0x20
    Description    REG_SZ    @%SystemRoot%\system32\w32time.dll,-201
    ObjectName    REG_SZ    NT AUTHORITY\LocalService
    ServiceSidType    REG_DWORD    0x1
    RequiredPrivileges    REG_MULTI_SZ    SeAuditPrivilege\0SeChangeNotifyPrivilege\0SeCreateGlobalPrivilege\0SeSystemTimePrivilege
    FailureActions    REG_BINARY    80510100000000000000000003000000140000000100000060EA000001000000C0D401000000000000000000

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Config
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\SecureTimeLimits
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Security
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TriggerInfo
```

**Comment by woftor** [comment]
So... apparantly The Key reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time\Start can have more than one setting to be enabled... I searched MSDN, cannot find it.

**Comment by fjl** [comment]
We can make it check for 0x2 too. The time sync check is best-effort anyway.

**Comment by luclu** [comment]
@fjl another occurance of `Start REG_DWORD 0x2` on win 10: https://github.com/ethereum/mist/issues/466

**Comment by fjl** [comment]
I will add the check for 0x2 in os-timesync. Will also fix the other linux issue there and release a new version.

**Comment by luclu** [comment]
We just released version **0.7.5** which contains an updated version of os-timesync.
https://github.com/ethereum/mist/releases/tag/0.7.5
Please give me a small ping-back if you still encounter any issues in this regard.

**Comment by SteffenIvanhoe** [comment]
The issue is not solved (or some new bug has been introduced). Here is my output of 
`reg query HKLM\SYSTEM\CurrentControlSet\Services\W32Time` (as requested):
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time
    Start    REG_DWORD    0x2
    DisplayName    REG_SZ    Windows-Zeitgeber
    ErrorControl    REG_DWORD    0x1
    ImagePath    REG_EXPAND_SZ    %SystemRoot%\system32\svchost.exe -k LocalService
    Type    REG_DWORD    0x20
    Description    REG_SZ    @%SystemRoot%\system32\w32time.dll,-201
    ObjectName    REG_SZ    NT AUTHORITY\LocalService
    ServiceSidType    REG_DWORD    0x1
    RequiredPrivileges    REG_MULTI_SZ    SeAuditPrivilege\0SeChangeNotifyPrivilege\0SeCreateGlobalPrivilege\0SeSystemTimePrivilege
    FailureActions    REG_BINARY    80510100000000000000000003000000140000000100000060EA000001000000C0D401000000000000000000

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Config
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\SecureTimeLimits
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\Security
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProviders
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TriggerInfo
```
I have explicitly checked and repeatedly synced clocks. They have a correct time. Either the clock you use is of or there is just a bug.

BTW: The displayed error message no longer contains the lines with "Your time" and "Real time".

**Comment by luclu** [comment]
@alexvandesande could you please check if os-timesync `1.0.6` got bundled or if it is still on `1.0.5`.

**Comment by nicksavers** [comment]
I receive the following error when running it on Ubuntu 16.04 LTS with 0.7.6 (did not occur with 0.7.5)

```
[2016-06-24 17:37:33.644] [ERROR] main - Couldn't get time from NTP time sync server. Error: can't find 'ntp enabled:' line in timedatectl output
    at /home/nick/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/node_modules/os-timesync/index.js:47:19
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
Error: can't find 'ntp enabled:' line in timedatectl output
    at /home/nick/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/node_modules/os-timesync/index.js:47:19
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

**Comment by luclu** [comment]
@fjl os-timesync `1.0.6` seems to be broken on linux. Getting the same error. Also it does not detect if NTP is deactivated.

**Comment by lgs** [comment]
I got ntp error on Ubuntu 16.04 too:

<pre>
[2016-06-26 21:54:21.054] [ERROR] main - Couldn't get time from NTP time sync server. Error: can't find 'ntp enabled:' line in timedatectl output
    at /home/lsoave/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/node_modules/os-timesync/index.js:47:19
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
Error: can't find 'ntp enabled:' line in timedatectl output
    at /home/lsoave/Ethereum-Wallet-linux64-0-7-6/resources/app.asar/node_modules/os-timesync/index.js:47:19
    at ChildProcess.exithandler (child_process.js:205:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
</pre>

<pre>
lsoave@basenode:~$ timedatectl
      Local time: lun 2016-06-27 00:48:45 CEST
  Universal time: dom 2016-06-26 22:48:45 UTC
        RTC time: dom 2016-06-26 22:48:45
       Time zone: Europe/Rome (CEST, +0200)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
</pre>


<pre>
lsoave@basenode:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial
</pre>

<pre>
lsoave@basenode:~$ file /home/lsoave/Ethereum-Wallet-linux64-0-7-6/Ethereum-Wallet
/home/lsoave/Ethereum-Wallet-linux64-0-7-6/Ethereum-Wallet: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.26, BuildID[sha1]=5924524d23575cf89b7cac088dd32c3d65057e9d, stripped
</pre>

**Comment by lgs** [comment]
@luclu 

... just a doubt, 
does **Ethereum-Wallet-linux64-0-7-6** use **ntpstat** call, to check the service ?

**Comment by fjl** [comment]
Regarding `Error: can't find 'ntp enabled:' line in timedatectl output`:
This error message is from an older version of os-timesync. The current version (1.0.6) [emits
a different message](https://github.com/fjl/os-timesync/blob/master/index.js#L47).

**Comment by luclu** [comment]
Unfortunately `1.0.6` did make it into `0.7.5`/`0.7.6` due to some problems with our packaging workflow. This is now resolved.  
Version `0.8` is scheduled for 5th of July.

**Comment by luclu** [comment]
Do you still encounter this with version `1.0.6` of os-timesync shipped with `0.8.0` and `0.8.1`?

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.

**Comment by gpowers01** [comment]
To add to this conversation as a non-standard Windows use case... I'm seeing this error on Windows systems (10, 2016, 2012r2, 7, etc.) when disabling the Windows time service completely and using a third party NTP client (Meinberg NTP client for Windows).  The local system time is currently offset on the system at 2ms with a clock discipline of less than 9ppm as a stratum 3 NTP client, that is showing an offset of -2ms to a straturm 2 NTP ref clock (local LAN NTP service), which is synced to a stratum 1 public server (Oklahoma State University) that has a GPS reference clock to within < 2 ms offset - all very low jitter values, normal poll and reach values, etc.  So, I'm confident that the time on my local system running the ethereum wallet is reasonably accurate to a high degree.  I'm seeing the time not synced error when I start the wallet, presumably due to the simple best effort registry check.  Possibly an option to disable this time check to suppress the error would be a viable alternative, such as an advanced option to declare that the user is using a third party time NTP service on windows machines?
