### ISSUE TITLE
Mist 0.11.1 doesn't work with geth 1.8.13

### ISSUE THREAD

**Issue by smartwombat** [ethereum/mist#4064]
See also https://github.com/ethereum/go-ethereum/issues/17372
Attempted workarounds failed.

Version: `0.11.1`
OS & Version: windows 10
Node version: `geth 1.8.13`
Number of blocks synchronized: testnet 3803586

It appears that Mist 0.11.1 is incapable of working with geth versions other than 1.8.11

from the logfile...
[2018-08-09T18:20:12.223] [INFO] Sockets/node-ipc - Connected!
[2018-08-09T18:20:12.705] [INFO] Sockets/3 - Connect to {"path":"\\\\.\\pipe\\geth.ipc"}
[2018-08-09T18:20:12.706] [INFO] Sockets/3 - Connected!
[2018-08-09T18:20:13.445] [INFO] ClientBinaryManager - Initializing...
[2018-08-09T18:20:13.445] [INFO] ClientBinaryManager - Resolving platform...
[2018-08-09T18:20:13.446] [INFO] ClientBinaryManager - Calculating possible clients...
[2018-08-09T18:20:13.447] [INFO] ClientBinaryManager - 1 possible clients.
[2018-08-09T18:20:13.448] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
[2018-08-09T18:20:13.449] [INFO] ClientBinaryManager - Verify Geth status ...
[2018-08-09T18:20:13.618] [INFO] updateChecker - App is up-to-date.
[2018-08-09T18:20:13.837] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-08-09T18:20:13.837] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
[2018-08-09T18:20:13.837] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-08-09T18:20:13.844] [INFO] ClientBinaryManager - Checking sanity for Geth ...
[2018-08-09T18:20:14.038] [ERROR] ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.8.11" in Geth output
    at Promise.resolve.then.then.then (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:632:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by evertonfraga** [comment]
Hi @smartwombat, sorry about that. It refuses to use a newer geth version unless we explicitly say it's compatible with Mist on our manifest file. 

we should turn it to a warning, probably. I believe it's fixed now. Would you be kind enough to give another run?

Cheers!

**Comment by Baalzamon512** [comment]
I too am getting this issue.
Ethereum Wallet version 0.11.1
Windows 10 x64
Geth 1.8.13

When firing up Ethereum Wallet it fails to connect with the same errors.  but if I'm in light mode it syncs up.  So Fast, Full sync is erroring but light mode is working.

**Comment by smartwombat** [comment]
@evertonfraga 
I see it's a source level change, and I don't have the facilities to make a build here (yet).
Sorry, I'm still at the stumbling on hands and knees stage.

**Comment by smartwombat** [comment]
@Baalzamon512 
I expect it works because the wallet will download geth 1.8.11 and then run it, ignoring whatever geth version you may already have running from another folder.
Then you have the usual proglem that the geth client won't sync the node at all in fast or full sync.
On Windows 10 I can get Parity to sync without problems, but not geth.

**Comment by Baalzamon512** [comment]
I am still getting this error 

ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.8.13" in Geth output
    at Promise.resolve.then.then.then (C:\Program Files\Ethereum-Wallet\resources\app.asar\node_modules\ethereum-client-binaries\src\index.js:632:17

Won't sync in light, fast or full.  I'm now running geth --fast option with --rpc and hoping that will force it to sync and send my ether....  As I've got a pending transaction not sent

**Comment by knysliuk** [comment]
Same issue after clicking to update Ethereum node... Multiple hour of white screen. Any advice, has this been resolved? 
<img width="797" alt="sssssss" src="https://user-images.githubusercontent.com/43155484/45328888-73ddaf80-b566-11e8-8dc9-6ae0ab44e55c.png">

Ethereum Wallet version 0.11.1
Mac 10.13.6
Geth 1.8.13 (trying to update to)

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
