### ISSUE TITLE
0.7.3 wallet not syncing: "too many open files"

### ISSUE THREAD

**Issue by More-decentral** [ethereum/mist#636]
![screen shot 2016-05-13 at 9 01 02 pm](https://cloud.githubusercontent.com/assets/16477843/15265281/46fd8ece-194e-11e6-9c55-cd896d14c815.png)

My Ethereum wallet is not syncing.  The log file indicates that "too many open files."  I have tried relaunched the wallet, and even restarted my iMac, but it won't sync.

Any ideas how to fix this issue?  Thanks.

Node type: geth/eth
OS: osx 10.10.5
Network type: main
Mist version: 0.7.3

**Comment by FaguiCurtain** [comment]
I have the same problem, using version 0.5.2 on MacOS X (El Capitan)
log file is the same

i have a window with "ethereum node needs to sync, please wait"
"downloading block 1,469,009 of 1,531,074  but its stuck there nothing happens....
tried relaunching MIST, tried rebooting the MAC... nothing did

where are my ETH gone ???

**Comment by luclu** [comment]
@More-decentral @FaguiCurtain Please update to `Ethereum-Wallet` 0.7.4, as this includes `geth` 1.4.4 which should fix this bug. I will close for now, but feel free to reopen if this is not solving the issue.

**Comment by FaguiCurtain** [comment]
it is not fixing the issue for me

**Comment by luclu** [comment]
regarding **brew**:
1. `brew update`
2. `brew uninstall ethereum` (might need to `brew unlock ethereum`)
3. `brew install ethereum`

**Comment by FaguiCurtain** [comment]
thanks i've updated both MIST to 0.7.4
and Geth with brew.

problem not solved

this is my log from GETH

E0519 01:19:08.904711 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 45e89b1e9f0d7ccb6fb482e25225b32f152871da7d91cdc9ffacdeb0734c8e34
E0519 01:19:08.904972 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 45e89b1e9f0d7ccb6fb482e25225b32f152871da7d91cdc9ffacdeb0734c8e34
E0519 01:19:08.906207 trie/secure_trie.go:74] Unhandled trie error: Missing trie node b58ed85cc29e94ea258e979ad4fdeebba886b21636174dde255ca901541e97b1
E0519 01:19:08.906437 trie/secure_trie.go:74] Unhandled trie error: Missing trie node b58ed85cc29e94ea258e979ad4fdeebba886b21636174dde255ca901541e97b1
E0519 01:19:08.909230 trie/secure_trie.go:74] Unhandled trie error: Missing trie node c63678ff44752776192976f2f80cb3a087579882fc800e776015097abc7f5a38
E0519 01:19:08.909419 trie/secure_trie.go:74] Unhandled trie error: Missing trie node c63678ff44752776192976f2f80cb3a087579882fc800e776015097abc7f5a38
E0519 01:19:08.910989 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 5c0b66a16a0906593de19cebd3f7de3b62899e5c4cfe630f5c83ca660639158b
E0519 01:19:08.911298 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 5c0b66a16a0906593de19cebd3f7de3b62899e5c4cfe630f5c83ca660639158b
E0519 01:19:08.912197 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59e42d8ee6a670335feebf0aa2a6d9042908aff832bc1a05f90b4a6860fce1c1
E0519 01:19:08.912414 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 59e42d8ee6a670335feebf0aa2a6d9042908aff832bc1a05f90b4a6860fce1c1
E0519 01:19:08.912703 trie/secure_trie.go:74] Unhandled trie error: Missing trie node a0a7575636e28626187ca70ee83cb67e84f6124c789e52d2adb4c72f18356db2
E0519 01:19:08.912899 trie/secure_trie.go:74] Unhandled trie error: Missing trie node a0a7575636e28626187ca70ee83cb67e84f6124c789e52d2adb4c72f18356db2
E0519 01:19:08.913143 trie/secure_trie.go:74] Unhandled trie error: Missing trie node a7255a65a8afec6138a2b15dc496ba4942e7cf8b523b3dffe9d7a41ddbcd83a2
E0519 01:19:08.913340 trie/secure_trie.go:74] Unhandled trie error: Missing trie node a7255a65a8afec6138a2b15dc496ba4942e7cf8b523b3dffe9d7a41ddbcd83a2
E0519 01:19:08.915702 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 8cf8653b4668bd030f8ddc04a5571eab9100864b8190df1ef86643d10bcf7c4b
E0519 01:19:08.915932 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 8cf8653b4668bd030f8ddc04a5571eab9100864b8190df1ef86643d10bcf7c4b
E0519 01:19:08.916724 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 0a86a8ae45853de97ed00025d464ffd1e41b819182d6dc8aaab2dd92e1d35120
E0519 01:19:08.917101 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 0a86a8ae45853de97ed00025d464ffd1e41b819182d6dc8aaab2dd92e1d35120
E0519 01:19:08.917479 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 4a70ba34b963ea465c746f4017983466a13eb56fad945299dc9d218e4d02d12b
E0519 01:19:08.917749 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 4a70ba34b963ea465c746f4017983466a13eb56fad945299dc9d218e4d02d12b
E0519 01:19:08.918074 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 4c8ede0bd3a75d9d5c911d29e850951d636dd90959d9bf8735e5e012af97d52c
E0519 01:19:08.918291 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 4c8ede0bd3a75d9d5c911d29e850951d636dd90959d9bf8735e5e012af97d52c
E0519 01:19:08.919453 trie/secure_trie.go:74] Unhandled trie error: Missing trie node a02db6185b3c544d9a5f0ffbb534fd14dba71170d77f2c43fbb92df47962b24c
E0519 01:19:08.919651 trie/secure_trie.go:74] Unhandled trie error: Missing trie node a02db6185b3c544d9a5f0ffbb534fd14dba71170d77f2c43fbb92df47962b24c
E0519 01:19:08.920175 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 97547bb15c0d0a084ea7ae33b25c680178dcfcf6d93a86e149173b6f25815a67
E0519 01:19:08.920393 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 97547bb15c0d0a084ea7ae33b25c680178dcfcf6d93a86e149173b6f25815a67

**Comment by luclu** [comment]
@More-decentral thank you for the feedback!
There seems to be a problem with your chain-replica geth can't recover on it's own.
Please make sure that no AV is interfering with it.
could you kindly rename your `chaindata`-folder under `~/Library/Ethereum/` to `chaindata.bak` and restart the wallet? Hope that solves your issue.

**Comment by FaguiCurtain** [comment]
im FaguiCurtain, no worries

i'm renaming the chaindata and restarted the wallet. it seems progressing, (from 0, now 32,000 blocks)
i hope it won't get stuck

in the meantime, can you tell me how to remove the DAO watch from GETH please ?

thank you

**Comment by luclu** [comment]
https://github.com/ethereum/mist/issues/616 please stick to one topic per thread (aka issue) in the future. ;)
