### ISSUE TITLE
Window completely white

### ISSUE THREAD

**Issue by ericblank** [ethereum/mist#75]
When I launch the wallet, the window opens but appears completely white. Moving my mouse over it causes cursor changes, so I think the fields are there

**Comment by chesterbitcoin** [comment]
I am having the exact same issue.  The wallet was installed on a fresh Ubuntu system.
Memory: 1.6 GiB
Processor: AMD C-50 Processor × 2 
Graphics: Gallium 0.4 on AMD PALM (DRM 2.43.0, LLVM 3.6.2)
OS: 64-bit

**Comment by noflag** [comment]
same issue on latest beta release

**Comment by Fehu16** [comment]
I also have this issues. mint 17.3 with command line Geth working

**Comment by Fehu16** [comment]
Ok i have a Nob guess, our wallets are white because we have no gas?

**Comment by frozeman** [comment]
Whats white? screenshot?

**Comment by noflag** [comment]
The entire app inside its window is completely white, but I believe UI elements are still there, since my cursor changes over spots. I'll get a screenshot later

**Comment by noflag** [comment]
screenshot: http://traktcal.chris-mulder.nl/feed/31/ericblank.ics

**Comment by robsyme** [comment]
Video of the issue: https://www.youtube.com/watch?v=hSyvIxCf4Bc

**Comment by frozeman** [comment]
Very interesting, thanks for the video. it seems like instead of loading mist, it loads the test page for testing the mist web views :)

Do you get the same effect, when you switch to the develop branch of the mist repo?
`git checkout develop`

I will try in ubuntu myself, but i only have an VM version, which is rather slow.

**Comment by robsyme** [comment]
I have the same issue in the devlop branch, sorry.

**Comment by diglos** [comment]
Hi,

got the same problem but I may have a hint about this. I have a hybrid gpu laptop (Intel/nvidia). This only happens with the intel graphics card. When I switch to Nvidia everything looks fine. Could be a DRM issue?

**Comment by gcmartinelli** [comment]
I confirm this issue. Running Ubuntu 15.10, also in a machine with Intel/Nvidia card. Haven't tested with the NVidia yet (because ubuntu doesn't like nvidia...).

**Comment by linagee** [comment]
If you have a white screen when you use:
`electron .`
Please try:
`electron . --ignore-gpu-blacklist`

**Comment by gcmartinelli** [comment]
ran ./Ethereum-wallet --ignore-gpu-blacklist

Program crashes after splash screen loading.

Output:
`$ ./Ethereum-Wallet --ignore-gpu-blacklist
CONNECT to IPC PATH: /home/xxx/.ethereum/geth.ipc
Geth connection FOUND
Checking node sync status...
Time between last block 6s
No sync necessary, starting app!
Loading Interface at file:///home/xxx/Desktop/Ethereum-Wallet-linux-x64-0-3-8/resources/app.asar/interface/wallet/index.html
CONNECT to IPC PATH: /home/thx/.ethereum/geth.ipc
Segmentation fault (core dumped)`

**Comment by linagee** [comment]
I guess some GPU drivers are incorrectly blacklisted and some are correctly blacklisted! @gcmartinelli I'd try using different graphics drivers if you can. (Switch from open source to proprietary or vise versa.)

**Comment by linagee** [comment]
@gcmartinelli I feel your pain. I've got a radeon 5800 card where the proprietary drivers also mess up Ubuntu. (Just found that the open source ones don't mess up Ubuntu, but then that chromium doesn't work for Mist, hah...)

(My definition of mess up here is: random corruption of screen data. Sometimes when scrolling up and down in Chrome.)

**Comment by gcarq** [comment]
Same with latest radeonsi drivers (mesa-11.1.1), `--ignore-gpu-blacklist` works as workaround.
OS: Arch linux (Linux 4.3.5-1-ck)

**Comment by frozeman** [comment]
I assume its a issue with some CSS we are using in the [dapp-styles](https://github.com/ethereum/dapp-styles) of the [wallet](https://github.com/ethereum/meteor-dapp-wallet).

As i can't reproduce the issue with the right/wrong hardware could anyone of you please play around with the dapps styles and see which parameter could cause this.

In the latest version i purposefully deactivated `webgl` for the windows.

Please to test do the following:

- run the mist wallet as described [here](https://github.com/ethereum/mist#installation)
- clone the dapp-styles into the wallet [`packages`](https://github.com/ethereum/meteor-dapp-wallet/tree/master/app/packages) folder
- make changes to the dapp styles, maybe in [containers.import.less](https://github.com/ethereum/dapp-styles/blob/master/containers.import.less) or [mixins.import.less](https://github.com/ethereum/dapp-styles/blob/master/mixins.import.less)

It should automatically then reload the wallet, so if it works it should just work.


Please also try before simply running `electron` without anything after, this should start the default electron webpage, if you can see this, that we should be able to make it work with the wallet as well.

**Comment by LGuappo** [comment]
`./Ethereum-Wallet --ignore-gpu-blacklist` worked for me too, but for the benefit of any noobs who come along struggle a bit like me, I would just add that first you need to open Terminal and use `ls` and `cd` to navigate to the folder where you have Ethereum-Wallet, then run: `./Ethereum-Wallet --ignore-gpu-blacklist`. It opened up Mist and I could see everything normally. Next time I opened from the GUI shortcut and it still opened normally.

**Comment by adityasuseno** [comment]
Same issue here on Ubuntu 14.04 LTS 64 bit Linux.
Getting black screen.

The workaround --ignore-gpu-blacklist  works

**Comment by maxxflyer** [comment]
Testing the latest release, nothing woked anymore and moved to ubuntu, same problem, white window (NO MENU HERE). 
After running ./Ethereum-Wallet --ignore-gpu-blacklist i can see the testnet, but I can't see the menu, so I can't switch to main net! 
Can you suggest the right hardware for Ethereum. I have 4 computers at home, the previous release worked for few days (only in one computer), until I moved to the latest and I lost all my work, since my password wasn't working anymore. and I couldn' find peers anymore. i then moved to ubuntu , everything worked like a sharm, but there is no MENU inside the wallet. Is there such thing like an "ethereum perfect basic hardware" I can buy out there? I started this adventure in January, 2 months and just a couple contracts created, and now I am again out the game. If my GPU libraries are messing up UBUNTU (I' m not so expert), there must be an offical hardware profile to buy in order to have a working system in one day. 
Is anyone having my same problem? I can't see the menu....

**Comment by frozeman** [comment]
On ubuntu the menu normally appears when you hover over the top menu bar, right? Try pressing the "alt" key.

**Comment by nairbv** [comment]
--ignore-gpu-blacklist worked for me, but this bug really makes a bad first impression and it seems like it has been reported a number of times.  E.g. it was raised here and closed but doesn't seem to be fixed:
https://github.com/ethereum/meteor-dapp-wallet/issues/78

I'm running mist 0.5.1 in LMDE.

**Comment by LGuappo** [comment]
After latest wallet upgrade it happens every time I launch wallet. So now I can only really launch via terminal using the ignore blacklist workaround each time.

**Comment by roland-c** [comment]
Same problem here on Ubuntu having NVIDIA card ... --ignore-gpu-blacklist doesn't work for me.

**Comment by chrispez** [comment]
Same here Roland. Has anyone found a fix/workaround for the Ubuntu and NVIDIA card combination?
Thanks

**Comment by chrispez** [comment]
Ah found a fix for those with NVIDIA in Ubuntu.

Run a search for additional drivers, then change from xorg open source driver to NIVIDIA proprietary and it should work.

**Comment by roland-c** [comment]
Weird, I had it working and now there is the blank screen again... nvidia is working on my box (OpenGL is working) but where previously --ignore-gpu-blacklist did work and Mist started properly now I get hte blank screen again...
Anyone has sen this behaviour, or anyone know what it is going on and how to fix this?

**Comment by wickles** [comment]
How do I fix this on Windows? (Windows 8.1 with AMD card)

**Comment by Lazarus1** [comment]
I am having a similar issue as well.
I am running MIST on windows 10 & a Integrated Intel® HD Graphics 4000 card.

![image](https://cloud.githubusercontent.com/assets/18330114/14382174/dd1617ac-fd59-11e5-8611-4858c2051678.png)

Any help on this matter would be great, I've searched a way out of this problem for a few days and still cant come up with a solution.

TY!

**Comment by frozeman** [comment]
can you start ..wallet.exe with `...exe --ignore-gpu-blacklist`?

**Comment by Lazarus1** [comment]
cant find a way to run that command, I'm running it inside the correct folder yet its still stays "not recognized"

**Comment by Lazarus1** [comment]
Ok so I was trying to perform that flag incorrectly the whole time, I figured it out. 
Now when I try to execute with the flag, it gives me errors. Its saying is missing certain dll files in my computer "nodes.dll, etc.." However I see every single dll in the latest wallet folder I downloaded.

**Comment by Lazarus1** [comment]
figured out how to run the flag, however when I execute problem still persists? I apologize in advance I am learning as I go with this new material, ty in advance for everything. 

![image](https://cloud.githubusercontent.com/assets/18330114/14385175/06a9cb14-fd6d-11e5-86a1-3dd2ebf2ec76.png)

**Comment by Lazarus1** [comment]
![image](https://cloud.githubusercontent.com/assets/18330114/14385220/4a24e98c-fd6d-11e5-80f9-58e74db2d71d.png)

Figured out how to run the flag but problem still persists, sorry for the back and fourth I am learning "as I go" with this new material. ty in advance for the help.

**Comment by Brownie79** [comment]
![mist error](https://cloud.githubusercontent.com/assets/3674978/14406648/25ead8a4-fe73-11e5-9180-7efa5ddb132c.PNG)
can confirm same error on windows with --ignore-gpu-blacklist as well

**Comment by floreslorca** [comment]
^ same error with Windows 7

**Comment by venticello** [comment]
This error win10, nvidia GTX 760

**Comment by 1957vespa** [comment]
I have the same issue 4X Radeon R9 280X running Ethereum-Wallet-win64-0-6-2  --ignore-gpu-blacklist leaves me with the same blank page

**Comment by Lazarus1** [comment]
Try installing the previous version, then go ahead and install the newer one.

**Comment by 1957vespa** [comment]
Installing the previous version, importing my wallet (from another computer) and then running new version worked just fine. Blank screen was when I installed 0.6.2 fresh .. running 0.6.1 , getting wallet set up THEN running 0.6.2 was a good workaround.

**Comment by luclu** [comment]
Not sure if related; does the meteor app not load?

![t kopie](https://cloud.githubusercontent.com/assets/10135872/14638974/4e754696-063a-11e6-9e69-5e0ff6660152.jpg)

**Versions**:
OS X **10.11.4**
Electron  **0.37.2**
Meteor **1.3.2.2**
Mist **0.7.1 / 0.7.0 / 0.6.2 / 0.6.1**

**Command/s**:
electron . --mode wallet --ignore-gpu-blacklist
electron . --mode wallet

**Comment by vogelito** [comment]
I'm seeing this in a fresh Ubuntu 14.04 install. `--ignore-gpu-blacklist` is not doing anything for me.

@chrispez do you have more detailed instructions? I'm not running NVIDIA (running Intel HD Graphics card), but hoping the path you went down to might be relevant for me as well.

**Comment by lazukars** [comment]
Still an issue with me. Tried on latest dev and master branches, and have used --ignore-gpu-blacklist. About two months ago Mist worked fine, but for over two months straight now, Mist opens to a blank screen. I hope, with every new release that this problem gets fixed once and for all, but after two months now, I've lost hope. 

OS : Ubuntu 14.04

**Comment by davedavis** [comment]
Same issue on 0.7.3 but when using remote desktop connection. Either MS RDP or Chrome Remote Desktop when remoting in to a Windows machine. Granted it's a niche use case but still. 

Native Intel graphics card. 

Works fine on the machine when I'm looking at it on the machine itself but when remoting in, it's white with the cursor changing over elements as described above.

**Comment by luclu** [comment]
@lazukars Ubuntu 14.04 works fine for me. What graphic-card and drivers are you using?

**Comment by ezredd** [comment]
i am having the same issue with mist 0.7.4 (but started one week ago with 0.7.3). I am running mac OS X 10.11.4

**Comment by luclu** [comment]
Unfortunately this is a problem upstream ([electron](https://github.com/electron/electron)). We will continue to integrate new versions that should slowly improve the situation as more graphic-cards are correctly blacklisted.
For now please have a look over here, we tried so summerize some tips: https://github.com/ethereum/mist/issues/599

**Comment by luclu** [comment]
Could you kindly check if you are still affected with our latest release **0.7.5**?
This contains electron 1.2.2 and a whole bunch of stability and synchronization improvements.
https://github.com/ethereum/mist/releases

**Comment by davedavis** [comment]
@luclu I don't think the 0.7.5 build for Windows is ready yet. Will definitely check as soon as it's live.

**Comment by luclu** [comment]
@davedavis it should work now ;)

**Comment by lazukars** [comment]
Just tried it on Ubuntu 14.04 with the following commands.

`$ cd mist
$ git pull && git submodule update
$ gulp update-nodes`

The gulp command errors out:

> Error: Cannot find module 'gulp-download'

**Comment by luclu** [comment]
@Lazarus1 you shouldn't need to run the develop version. Anyways you will need to `npm update/install`.

**Comment by lazukars** [comment]
Thanks! Can you get that in the documentation?

**Comment by lazukars** [comment]
Still getting the blank white screen.

OS: Ubuntu 14.04
Mist: 0.7.5

**Comment by luclu** [comment]
@Lazarus1 done: https://github.com/ethereum/mist/pull/852

**Comment by lazukars** [comment]
Thanks for that. Much appreciated! 

On another note, I just tried the new Mist 0.7.5 version after updated the npm packages. Still getting the white screen.

**Comment by lazukars** [comment]
This error happens when running `electron .` in side mist dir.

> [2016-06-18 17:39:41.567] [ERROR] EthereumNode - Unable to read from /home/me/.con
fig/Mist/network { [Error: ENOENT: no such file or directory, open '/home/lme/.conf
ig/Mist/network']

I nuked the mist config folder awhile back, to see if that would resolve this issue. That's why it's gone. What do you suggest?

**Comment by luclu** [comment]
@lazukars please join the gitter channel and ping me, so the other subscribers don't get flooded.

**Comment by davedavis** [comment]
@luclu

In my particular use case, remoting in, on this issue, it seems to be resolved. Not getting the white UI on Windows 10 RDP. 

From my perspective thus us resolved, but it seems other OS's are not so if you need anything from my end, let me know. 

Also, not sure if it's related but my Nvidia display driver was updated since this issue was posted. Doubt it's related but worth noting.

**Comment by luclu** [comment]
Could you kindly check how version `0.8.0` is behaving on this?

**Comment by wickles** [comment]
Same issue still.

**Comment by ragnar321** [comment]
If it helps anyone running Linux in Virtualbox (Debian testing on a Windows 10 host), unticking 3d acceleration in the VirtualBox settings allows the screens to be visible for me. The gpu blacklist flag had no affect. (Mist 0.8.1)

**Comment by Tectract** [comment]
same issue, I think.
> electron .
results in a nothing blank splash screen on my main development machine, no apparent error messages, just nothing happens.
this is version 0.8.4

**Comment by luclu** [comment]
@Tectract do you use the development environment? Version `0.8.4` is not yet released. ;)

**Comment by Tectract** [comment]
Hmmmm, yes I guess I'm on dev branch, I just git cloned and away I went without switching to master I guess. I'm somewhat convinced this is a graphics driver interaction though, since the same code works just fine on my other machine. Doesn't seem to be anything particular to dev branch at this moment. As Ragnar said, it seems that some sort of 3D acceleration is being used and it's holding up the display of the flash screen, causing the program to be unusable.

**Comment by evertonfraga** [comment]
@Tectract do you have anything close to an image of your (clean) OS?
Or something detailed about your OS, driver, etc. I want to replicate your issue on a virtual machine.

**Comment by Tectract** [comment]
This is on a linux mint machine that I haven't done dist-upgrade on for a while.

Linux ComputerName 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I think the issue is actually possibly related to the graphics driver and maybe some interaction with AMD settings. 

01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Cypress HDMI Audio [Radeon HD 5800 Series]

and it's using the fglrx driver, hmmmm.... 

Another option here, I noticed that sometimes if the meteor server isn't running or the full node isn't running, then it will hang on a blank splash screen even on my other machine. This should be more explicitly handled in the code, it seems.

**Comment by vagabondan** [comment]
@ragnar321 Many thanks! Unsetting 3d-acceleration in VirtualBox really helped!
